name: context example

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: |
           echo "Action! $MY_ACTION"
           echo "ACTOR! $MY_ACTOR"
        env:
            MY_ACTION: ${{github.action}}
            MY_ACTOR: ${{github.actor}}


