name: context example

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "MY_ACTION=${{ github.action }}" >> $GITHUB_ENV
        
      - name: "my step"
        run: echo "Hello! $MY_ACTION"
        env:
            MY_ACTION: ${{github.action}}
            MY_ACTOR: ${{github.actor}}


